use_frameworks!

platform :ios, '9.0'

target 'WKWebViewJSBridge_Example' do
  pod 'WKWebViewJSBridge', :path => '../'

  target 'WKWebViewJSBridge_Tests' do
    inherit! :search_paths

    
  end
end
